#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

old_domain=$YNH_APP_OLD_DOMAIN
old_path="/"

new_domain=$YNH_APP_NEW_DOMAIN
new_path="/"

app=$YNH_APP_INSTANCE_NAME

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Loading installation settings..."

# Needed for helper "ynh_add_nginx_config"
final_path=$(ynh_app_setting_get "$app" final_path)

# Add settings here as needed by your application
#db_name=$(ynh_app_setting_get "$app" db_name)
#db_pwd=$(ynh_app_setting_get $app db_pwd)

#=================================================
# CHECK WHICH PARTS SHOULD BE CHANGED
#=================================================

change_domain=0
if [ "$old_domain" != "$new_domain" ]
then
	change_domain=1
fi

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_print_info "Updating nginx web server configuration..."

nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf

# Change the domain for nginx
if [ $change_domain -eq 1 ]
then
	# Delete file checksum for the old conf file location
	ynh_delete_file_checksum "$nginx_conf_path"
	mv "$nginx_conf_path" "/etc/nginx/conf.d/$new_domain.d/$app.conf"
	# Store file checksum for the new config file location
	ynh_store_file_checksum "/etc/nginx/conf.d/$new_domain.d/$app.conf"
fi

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# UPDATE CONFIG FILE
#=================================================

config="$final_path/.env"
ynh_replace_string "APP_URL=.*"  "APP_URL=https://$new_domain"   "$config"
ynh_replace_string "ADMIN_DOMAIN=.*"  "ADMIN_DOMAIN=\"$new_domain\""   "$config"
ynh_replace_string "APP_DOMAIN=.*"  "APP_DOMAIN=\"$new_domain\""   "$config"
ynh_replace_string "MAIL_FROM_ADDRESS=.*"  "MAIL_FROM_ADDRESS=\"pixelfed@$new_domain\""   "$config"

#=================================================
# STORE THE CHECKSUM OF THE CONFIG FILE
#=================================================

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "$config"

#=================================================
# APPLY CHANGES
#=================================================

pushd "$final_path"
	php7.2 artisan config:clear
	php7.2 artisan config:cache
	php7.2 artisan route:clear
	php7.2 artisan route:cache
	php7.2 artisan horizon:purge
popd
#=================================================
# GENERIC FINALISATION
#=================================================
# RELOAD NGINX
#=================================================
ynh_print_info "Reloading nginx web server..."

systemctl reload nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Change of URL completed for $app"
