#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SUPERVISOR SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# UPDATE CONFIG FILE
#=================================================
ynh_script_progression "Updating config file..."

config="$install_dir/.env"
ynh_backup_if_checksum_is_different "$config"
ynh_replace --match="APP_URL=.*"           --replace="APP_URL=https://$new_domain"                --file="$config"
ynh_replace --match="ADMIN_DOMAIN=.*"      --replace="ADMIN_DOMAIN=\"$new_domain\""               --file="$config"
ynh_replace --match="APP_DOMAIN=.*"        --replace="APP_DOMAIN=\"$new_domain\""                 --file="$config"
ynh_replace --match="MAIL_FROM_ADDRESS=.*" --replace="MAIL_FROM_ADDRESS=\"pixelfed@$new_domain\"" --file="$config"

# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum "$config"

#=================================================
# APPLY CHANGES
#=================================================
ynh_script_progression "Applying changes..."

pushd "$install_dir"
	php$php_version artisan config:clear
	php$php_version artisan config:cache
	php$php_version artisan route:clear
	php$php_version artisan route:cache
	php$php_version artisan horizon:purge
popd

#=================================================
# START SUPERVISOR SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
