#!/bin/bash
source /usr/share/yunohost/helpers

get__php_upload_max_filesize() {
ynh_app_setting_get --key=php_upload_max_filesize  | sed 's/M$//' # number required in config panel
}

set__php_upload_max_filesize() {
    ynh_replace --match='client_max_body_size [^"]*' --replace="client_max_body_size  ${php_upload_max_filesize}M  ;" --file="/etc/nginx/conf.d/$domain.d/$app.conf"
    ynh_store_file_checksum "/etc/nginx/conf.d/$domain.d/$app.conf"
    ynh_app_setting_set --key=php_post_max_size --value="${php_upload_max_filesize}M"
    ynh_app_setting_set --key=php_upload_max_filesize --value="${php_upload_max_filesize}M"
    php_upload_max_filesize=$(ynh_app_setting_get --key=php_upload_max_filesize) # update php_upload_max_filesize
    ynh_config_add_phpfpm
    ynh_print_info "upload max file size has been updated"
}

ynh_abort_if_errors
ynh_app_config_run $1
