#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

timezone=$(cat /etc/timezone)
ynh_app_setting_set_default --key=language --value="fr"
ynh_app_setting_set_default --key=php_upload_max_filesize --value=100M
ynh_app_setting_set_default --key=php_post_max_size --value=100M
ynh_app_setting_set_default --key=php_max_file_uploads --value=100M
ynh_app_setting_set_default --key=php_max_execution_time --value=600

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If app_key doesn't exist, retrieve it
if [ -z "${app_key:-}" ]; then
	ynh_script_progression "Retrieving app_key..."
	app_key=$(grep -oP "APP_KEY=\Kbase64.*" "$install_dir/.env")
	ynh_app_setting_set --key=app_key --value="$app_key"
fi

if ynh_app_upgrading_from_version_before_or_equal_to 0.10.9~ynh3; then
	ynh_script_progression "Ensuring upgrade compatibility to 0.10.9~ynh3..."

	if ynh_hide_warnings yunohost service status ${app}-horizon >/dev/null
	then
		ynh_script_progression "Removing ${app}-horizon service..."
		yunohost service remove "${app}-horizon"
	fi
fi

# Fix old email configs
if ynh_app_upgrading_from_version_before 0.11.8~ynh5 ; then
	ynh_replace_regex --match="MAIL_DRIVER=[^\\n]*" --replace="MAIL_DRIVER=sendmail" --file="$install_dir/.env" # two \\ because it's in a ""
	ynh_replace_regex --match="MAIL_HOST=[^\\n]*" --replace="MAIL_HOST=127.0.0.1" --file="$install_dir/.env" # two \\ because it's in a ""
	ynh_replace_regex --match="MAIL_USERNAME=[^\\n]*" --replace="MAIL_USERNAME=$app" --file="$install_dir/.env" # two \\ because it's in a ""
	ynh_replace_regex --match="MAIL_PASSWORD=[^\\n]*" --replace="MAIL_PASSWORD=$mail_pwd" --file="$install_dir/.env" # two \\ because it's in a ""
	ynh_replace_regex --match="MAIL_FROM_ADDRESS=pixelfed" --replace=`MAIL_FROM_ADDRESS="$app"` --file="$install_dir/.env"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep=".env"

chmod 600 "$install_dir/.env"

#=================================================
# PATCHING SOURCE
#=================================================
ynh_script_progression "Patching source files..."

# Prevent privilege escalation by injecting commands in an email name
# This described in more detail on the manpage https://www.postfix.org/sendmail.1.html under security
ynh_replace --match="'/usr/sbin/sendmail -bs'" --replace="'/usr/sbin/sendmail -bs -- '" --file=$install_dir/config/mail.php

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

mkdir -p "/var/log/$app/"
touch "/var/log/$app/${app}-horizon.log"
chown -R $app: "/var/log/$app/"
chmod -R 600 "/var/log/$app/"

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add "$app" --description="Federated Image Sharing" --log="/var/log/$app/$app.log"

#=================================================
# UPDATE COMPOSER DEPENDENCIES
#=================================================
ynh_script_progression "Updating composer..."

ynh_composer_exec self-update --2

ynh_composer_exec update

#=================================================
# PATCH PERMISSIONS for v0.11.5 versions and higher
#=================================================
ynh_script_progression "Patching permissions (for version 0.11.5 and newer)..."

# Default configuration doesn't work
ynh_replace --match="'private' => 0700," --replace="'private' => 0750," --file=$install_dir/config/filesystems.php

# Repair permissions for files created after v0.11.5 and before this patch
if [ -d "$install_dir/public/storage/m/_v2/" ]; then
  chmod 750 -R "$install_dir/public/storage/m/_v2/"* # all files subdirectories (picture folders) should be readable and executable. But if there is no picture, there is no /*/*
  chmod 770 "$install_dir/public/storage/m/_v2/"* # users folders should be 770
  chmod 770 "$install_dir/public/storage/m/_v2/" # this should be 770
  chown -R :www-data "$install_dir/public/storage/m/_v2/" # Fix the mess following packaging v2 upgrade - and make sure proper group owner is set.
fi

#=================================================
# DEPLOYMENT
#=================================================
ynh_script_progression "Deploying $app..."

artisan="ynh_exec_as_app php$php_version artisan"
artisan_root="php$php_version artisan"

pushd "$install_dir"
	$artisan horizon:install
	$artisan horizon:publish
	$artisan passport:keys --force
	$artisan_root config:clear
	$artisan config:cache
	$artisan_root route:clear
	$artisan route:cache
	$artisan_root view:clear
	$artisan view:cache
	$artisan storage:link
	$artisan migrate --force
	$artisan horizon:purge
	$artisan import:cities 2>/dev/null
	$artisan instance:actor
	$artisan passport:client --personal <<< "\\n"
popd

# patch the database to fix a bug which prevent to upload images
# see: https://github.com/pixelfed/pixelfed/issues/5217
ynh_psql_db_shell <<< "alter table media alter column caption drop not null;"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
